# Generated by Django 4.2 on 2023-04-12 09:33

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=20, verbose_name='first name')),
                ('last_name', models.CharField(max_length=20, verbose_name='last name')),
                ('phone_number', models.CharField(max_length=14, verbose_name='phone number')),
                ('demo_login', models.CharField(max_length=12, verbose_name='demo login')),
                ('demo_password', users.models.CustomPasswordField(max_length=15, verbose_name='demo password')),
                ('demo_server', models.CharField(max_length=20, verbose_name='demo server')),
                ('live_login', models.CharField(max_length=12, verbose_name='live login')),
                ('live_password', users.models.CustomPasswordField(max_length=15, verbose_name='live password')),
                ('live_server', models.CharField(max_length=20, verbose_name='live server')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
